### ISSUE TITLE
path error in makefile

### ISSUE THREAD

**Issue by jonathonross** [heytoaster/VirtualUSBDevice#1]
The case to the path in the makefile versus the directory structure is off. 

here's what's in the Makefile:
OBJECTS=src/main.o

But the directory is ./Src/main.cpp

could change it in the makefile or the directory depending on what was desired.

**Comment by davetoaster** [comment]
Thanks @jonathonross, this should be fixed now. macOS case insensitivity strikes again 😆 (I run Linux in a VM on macOS...)
