### ISSUE TITLE
Duplicate entries in submodule file

### ISSUE THREAD

**Issue by jonathonross** [heytoaster/VirtualUSBDevice#2]
Looks like another path error in the git modules file

```
[submodule "lib/Toastbox"]
	path = lib/Toastbox
	url = git@github.com:heytoaster/Toastbox.git
[submodule "Lib/Toastbox"]
	path = Lib/Toastbox
	url = git@github.com:heytoaster/Toastbox.git
```

The makefile uses Lib rather than lib. I also found it easier to use url = https://github.com/heytoaster/Toastbox.git for the submodule than set up the SSL certificate. Not sure if others will have access, but either way this doesn't need to be there twice, I thin.

**Comment by amoldhamale1105** [comment]
@davekeck You need to authorize people to create branches and open pull requests. I have addressed this and another open issue and also fixed some build errors but unable to raise a PR.

**Comment by davetoaster** [comment]
Thanks @jonathonross, this should be fixed now
